# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_tracker_app.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(780, 491)
        mainWindow.setMinimumSize(QtCore.QSize(646, 383))
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralWidget)
        self.tab_widget.setObjectName("tab_widget")
        self.mod_select_tab = QtWidgets.QWidget()
        self.mod_select_tab.setObjectName("mod_select_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mod_select_tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(self.mod_select_tab)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_mod_select = QtWidgets.QLabel(self.widget_5)
        self.label_mod_select.setObjectName("label_mod_select")
        self.gridLayout_5.addWidget(self.label_mod_select, 0, 0, 1, 1)
        self.model_comboBox = QtWidgets.QComboBox(self.widget_5)
        self.model_comboBox.setObjectName("model_comboBox")
        self.gridLayout_5.addWidget(self.model_comboBox, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 319, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 1, 1, 1)
        self.set_mod_btn = QtWidgets.QPushButton(self.widget_5)
        self.set_mod_btn.setObjectName("set_mod_btn")
        self.gridLayout_5.addWidget(self.set_mod_btn, 3, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget_5)
        self.model_view = ModelSelectWidget(self.mod_select_tab)
        self.model_view.setMinimumSize(QtCore.QSize(611, 0))
        self.model_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.model_view.setObjectName("model_view")
        self.horizontalLayout.addWidget(self.model_view)
        self.tab_widget.addTab(self.mod_select_tab, "")
        self.fg_tab = QtWidgets.QWidget()
        self.fg_tab.setObjectName("fg_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fg_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.fg_tab)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fg_par_label = QtWidgets.QLabel(self.widget_4)
        self.fg_par_label.setObjectName("fg_par_label")
        self.gridLayout_4.addWidget(self.fg_par_label, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(575, 288, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 10, 1)
        self.n_threads_label = QtWidgets.QLabel(self.widget_4)
        self.n_threads_label.setObjectName("n_threads_label")
        self.gridLayout_4.addWidget(self.n_threads_label, 1, 0, 1, 1)
        self.n_threads_spin = QtWidgets.QSpinBox(self.widget_4)
        self.n_threads_spin.setObjectName("n_threads_spin")
        self.gridLayout_4.addWidget(self.n_threads_spin, 1, 1, 1, 1)
        self.nx_label = QtWidgets.QLabel(self.widget_4)
        self.nx_label.setObjectName("nx_label")
        self.gridLayout_4.addWidget(self.nx_label, 2, 0, 1, 1)
        self.nx_spin = QtWidgets.QSpinBox(self.widget_4)
        self.nx_spin.setObjectName("nx_spin")
        self.gridLayout_4.addWidget(self.nx_spin, 2, 1, 1, 1)
        self.ny_label = QtWidgets.QLabel(self.widget_4)
        self.ny_label.setObjectName("ny_label")
        self.gridLayout_4.addWidget(self.ny_label, 3, 0, 1, 1)
        self.ny_spin = QtWidgets.QSpinBox(self.widget_4)
        self.ny_spin.setObjectName("ny_spin")
        self.gridLayout_4.addWidget(self.ny_spin, 3, 1, 1, 1)
        self.nz_label = QtWidgets.QLabel(self.widget_4)
        self.nz_label.setObjectName("nz_label")
        self.gridLayout_4.addWidget(self.nz_label, 4, 0, 1, 1)
        self.nz_spin = QtWidgets.QSpinBox(self.widget_4)
        self.nz_spin.setObjectName("nz_spin")
        self.gridLayout_4.addWidget(self.nz_spin, 4, 1, 1, 1)
        self.ds_label = QtWidgets.QLabel(self.widget_4)
        self.ds_label.setObjectName("ds_label")
        self.gridLayout_4.addWidget(self.ds_label, 5, 0, 1, 1)
        self.ds_spin = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.ds_spin.setObjectName("ds_spin")
        self.gridLayout_4.addWidget(self.ds_spin, 5, 1, 1, 1)
        self.x0_label = QtWidgets.QLabel(self.widget_4)
        self.x0_label.setObjectName("x0_label")
        self.gridLayout_4.addWidget(self.x0_label, 6, 0, 1, 1)
        self.x0_spin = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.x0_spin.setObjectName("x0_spin")
        self.gridLayout_4.addWidget(self.x0_spin, 6, 1, 1, 1)
        self.y0_label = QtWidgets.QLabel(self.widget_4)
        self.y0_label.setObjectName("y0_label")
        self.gridLayout_4.addWidget(self.y0_label, 7, 0, 1, 1)
        self.y0_spin = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.y0_spin.setObjectName("y0_spin")
        self.gridLayout_4.addWidget(self.y0_spin, 7, 1, 1, 1)
        self.z0_label = QtWidgets.QLabel(self.widget_4)
        self.z0_label.setObjectName("z0_label")
        self.gridLayout_4.addWidget(self.z0_label, 8, 0, 1, 1)
        self.z0_spin = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.z0_spin.setObjectName("z0_spin")
        self.gridLayout_4.addWidget(self.z0_spin, 8, 1, 1, 1)
        self.set_fg_par_button = QtWidgets.QPushButton(self.widget_4)
        self.set_fg_par_button.setObjectName("set_fg_par_button")
        self.gridLayout_4.addWidget(self.set_fg_par_button, 9, 0, 1, 2)
        self.calc_fg_button = QtWidgets.QPushButton(self.widget_4)
        self.calc_fg_button.setObjectName("calc_fg_button")
        self.gridLayout_4.addWidget(self.calc_fg_button, 10, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(708, 72, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 11, 0, 1, 3)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.tab_widget.addTab(self.fg_tab, "")
        self.fit_tab = QtWidgets.QWidget()
        self.fit_tab.setObjectName("fit_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fit_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rawFrameView = ScaleModelWidget(self.fit_tab)
        self.rawFrameView.setMinimumSize(QtCore.QSize(0, 311))
        self.rawFrameView.setObjectName("rawFrameView")
        self.verticalLayout_2.addWidget(self.rawFrameView)
        self.widget = QtWidgets.QWidget(self.fit_tab)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 96))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_raw_label = QtWidgets.QLabel(self.widget)
        self.frame_raw_label.setObjectName("frame_raw_label")
        self.gridLayout_2.addWidget(self.frame_raw_label, 0, 0, 1, 1)
        self.frameSelectRaw = QtWidgets.QSpinBox(self.widget)
        self.frameSelectRaw.setObjectName("frameSelectRaw")
        self.gridLayout_2.addWidget(self.frameSelectRaw, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.set_par_button = QtWidgets.QPushButton(self.widget)
        self.set_par_button.setObjectName("set_par_button")
        self.gridLayout_2.addWidget(self.set_par_button, 1, 3, 1, 1)
        self.length_table = QtWidgets.QTableWidget(self.widget)
        self.length_table.setObjectName("length_table")
        self.length_table.setColumnCount(0)
        self.length_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.length_table, 0, 1, 2, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.tab_widget.addTab(self.fit_tab, "")
        self.seg_tab = QtWidgets.QWidget()
        self.seg_tab.setObjectName("seg_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.seg_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.segFrameView = ImageSegmentWidget(self.seg_tab)
        self.segFrameView.setObjectName("segFrameView")
        self.verticalLayout_3.addWidget(self.segFrameView)
        self.widget_2 = QtWidgets.QWidget(self.seg_tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_seg_label = QtWidgets.QLabel(self.widget_2)
        self.frame_seg_label.setObjectName("frame_seg_label")
        self.gridLayout.addWidget(self.frame_seg_label, 0, 0, 1, 1)
        self.body_th_label = QtWidgets.QLabel(self.widget_2)
        self.body_th_label.setObjectName("body_th_label")
        self.gridLayout.addWidget(self.body_th_label, 0, 1, 1, 1)
        self.wing_th_label = QtWidgets.QLabel(self.widget_2)
        self.wing_th_label.setObjectName("wing_th_label")
        self.gridLayout.addWidget(self.wing_th_label, 0, 2, 1, 1)
        self.sigma_label = QtWidgets.QLabel(self.widget_2)
        self.sigma_label.setObjectName("sigma_label")
        self.gridLayout.addWidget(self.sigma_label, 0, 3, 1, 1)
        self.K_label = QtWidgets.QLabel(self.widget_2)
        self.K_label.setObjectName("K_label")
        self.gridLayout.addWidget(self.K_label, 0, 4, 1, 1)
        self.min_body_label = QtWidgets.QLabel(self.widget_2)
        self.min_body_label.setObjectName("min_body_label")
        self.gridLayout.addWidget(self.min_body_label, 0, 5, 1, 1)
        self.min_wing_label = QtWidgets.QLabel(self.widget_2)
        self.min_wing_label.setObjectName("min_wing_label")
        self.gridLayout.addWidget(self.min_wing_label, 0, 6, 1, 2)
        self.frame_seg_spin = QtWidgets.QSpinBox(self.widget_2)
        self.frame_seg_spin.setObjectName("frame_seg_spin")
        self.gridLayout.addWidget(self.frame_seg_spin, 1, 0, 1, 1)
        self.body_th_spin = QtWidgets.QSpinBox(self.widget_2)
        self.body_th_spin.setObjectName("body_th_spin")
        self.gridLayout.addWidget(self.body_th_spin, 1, 1, 1, 1)
        self.wing_th_spin = QtWidgets.QSpinBox(self.widget_2)
        self.wing_th_spin.setObjectName("wing_th_spin")
        self.gridLayout.addWidget(self.wing_th_spin, 1, 2, 1, 1)
        self.sigma_spin = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.sigma_spin.setObjectName("sigma_spin")
        self.gridLayout.addWidget(self.sigma_spin, 1, 3, 1, 1)
        self.K_spin = QtWidgets.QSpinBox(self.widget_2)
        self.K_spin.setObjectName("K_spin")
        self.gridLayout.addWidget(self.K_spin, 1, 4, 1, 1)
        self.min_body_spin = QtWidgets.QSpinBox(self.widget_2)
        self.min_body_spin.setObjectName("min_body_spin")
        self.gridLayout.addWidget(self.min_body_spin, 1, 5, 1, 1)
        self.min_wing_spin = QtWidgets.QSpinBox(self.widget_2)
        self.min_wing_spin.setObjectName("min_wing_spin")
        self.gridLayout.addWidget(self.min_wing_spin, 1, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 7, 1, 1)
        self.update_button = QtWidgets.QPushButton(self.widget_2)
        self.update_button.setObjectName("update_button")
        self.gridLayout.addWidget(self.update_button, 1, 8, 1, 1)
        self.check_tethered = QtWidgets.QCheckBox(self.widget_2)
        self.check_tethered.setObjectName("check_tethered")
        self.gridLayout.addWidget(self.check_tethered, 2, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.tab_widget.addTab(self.seg_tab, "")
        self.pcl_tab = QtWidgets.QWidget()
        self.pcl_tab.setObjectName("pcl_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pcl_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bbox_view = BBoxWidget(self.pcl_tab)
        self.bbox_view.setMinimumSize(QtCore.QSize(740, 371))
        self.bbox_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bbox_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bbox_view.setObjectName("bbox_view")
        self.verticalLayout_4.addWidget(self.bbox_view)
        self.widget_3 = QtWidgets.QWidget(self.pcl_tab)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_bbox_label = QtWidgets.QLabel(self.widget_3)
        self.frame_bbox_label.setObjectName("frame_bbox_label")
        self.gridLayout_3.addWidget(self.frame_bbox_label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 7, 1, 1)
        self.frame_bbox_spin = QtWidgets.QSpinBox(self.widget_3)
        self.frame_bbox_spin.setObjectName("frame_bbox_spin")
        self.gridLayout_3.addWidget(self.frame_bbox_spin, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(580, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        self.wxsi_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.wxsi_spin.setObjectName("wxsi_spin")
        self.gridLayout_3.addWidget(self.wxsi_spin, 1, 2, 1, 1)
        self.wtheta_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.wtheta_spin.setObjectName("wtheta_spin")
        self.gridLayout_3.addWidget(self.wtheta_spin, 1, 3, 1, 1)
        self.wlength_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.wlength_spin.setObjectName("wlength_spin")
        self.gridLayout_3.addWidget(self.wlength_spin, 1, 4, 1, 1)
        self.wvolume_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.wvolume_spin.setObjectName("wvolume_spin")
        self.gridLayout_3.addWidget(self.wvolume_spin, 1, 5, 1, 1)
        self.cone_angle_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.cone_angle_spin.setObjectName("cone_angle_spin")
        self.gridLayout_3.addWidget(self.cone_angle_spin, 1, 6, 1, 1)
        self.cone_height_spin = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.cone_height_spin.setObjectName("cone_height_spin")
        self.gridLayout_3.addWidget(self.cone_height_spin, 1, 7, 1, 1)
        self.bbox_view_btn = QtWidgets.QPushButton(self.widget_3)
        self.bbox_view_btn.setObjectName("bbox_view_btn")
        self.gridLayout_3.addWidget(self.bbox_view_btn, 1, 8, 1, 1)
        self.blr_view_btn = QtWidgets.QPushButton(self.widget_3)
        self.blr_view_btn.setObjectName("blr_view_btn")
        self.gridLayout_3.addWidget(self.blr_view_btn, 1, 9, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.tab_widget.addTab(self.pcl_tab, "")
        self.model_proj_tab = QtWidgets.QWidget()
        self.model_proj_tab.setObjectName("model_proj_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.model_proj_tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mod_proj_view = ModelProjectionWidget(self.model_proj_tab)
        self.mod_proj_view.setMinimumSize(QtCore.QSize(0, 371))
        self.mod_proj_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mod_proj_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mod_proj_view.setObjectName("mod_proj_view")
        self.verticalLayout_6.addWidget(self.mod_proj_view)
        self.widget_6 = QtWidgets.QWidget(self.model_proj_tab)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(657, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 1, 2, 1)
        self.show_dest_pts = QtWidgets.QPushButton(self.widget_6)
        self.show_dest_pts.setObjectName("show_dest_pts")
        self.gridLayout_6.addWidget(self.show_dest_pts, 0, 2, 2, 1)
        self.show_src_pts = QtWidgets.QPushButton(self.widget_6)
        self.show_src_pts.setObjectName("show_src_pts")
        self.gridLayout_6.addWidget(self.show_src_pts, 0, 3, 2, 1)
        self.show_mdl = QtWidgets.QPushButton(self.widget_6)
        self.show_mdl.setObjectName("show_mdl")
        self.gridLayout_6.addWidget(self.show_mdl, 0, 4, 2, 1)
        self.calc_align = QtWidgets.QPushButton(self.widget_6)
        self.calc_align.setObjectName("calc_align")
        self.gridLayout_6.addWidget(self.calc_align, 0, 5, 2, 1)
        self.model_proj_spin = QtWidgets.QSpinBox(self.widget_6)
        self.model_proj_spin.setObjectName("model_proj_spin")
        self.gridLayout_6.addWidget(self.model_proj_spin, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.widget_6)
        self.tab_widget.addTab(self.model_proj_tab, "")
        self.frame_proj_tab = QtWidgets.QWidget()
        self.frame_proj_tab.setObjectName("frame_proj_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_proj_tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_proj_view = ImageProjectionsWidget(self.frame_proj_tab)
        self.frame_proj_view.setMinimumSize(QtCore.QSize(0, 371))
        self.frame_proj_view.setObjectName("frame_proj_view")
        self.verticalLayout_7.addWidget(self.frame_proj_view)
        self.widget_7 = QtWidgets.QWidget(self.frame_proj_tab)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(549, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 0, 1, 2, 1)
        self.frame_proj_spin = QtWidgets.QSpinBox(self.widget_7)
        self.frame_proj_spin.setObjectName("frame_proj_spin")
        self.gridLayout_7.addWidget(self.frame_proj_spin, 1, 0, 1, 1)
        self.calc_proj = QtWidgets.QPushButton(self.widget_7)
        self.calc_proj.setObjectName("calc_proj")
        self.gridLayout_7.addWidget(self.calc_proj, 1, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_7)
        self.tab_widget.addTab(self.frame_proj_tab, "")
        self.verticalLayout.addWidget(self.tab_widget)
        mainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mainWindow)
        self.tab_widget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "flight tracker app"))
        self.label_mod_select.setText(_translate("mainWindow", "select model:"))
        self.set_mod_btn.setText(_translate("mainWindow", "set model"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.mod_select_tab), _translate("mainWindow", "Model Selection"))
        self.fg_par_label.setText(_translate("mainWindow", "Focal Grid parameters:"))
        self.n_threads_label.setText(_translate("mainWindow", "N threads"))
        self.nx_label.setText(_translate("mainWindow", "Nx:"))
        self.ny_label.setText(_translate("mainWindow", "Ny:"))
        self.nz_label.setText(_translate("mainWindow", "Nz:"))
        self.ds_label.setText(_translate("mainWindow", "ds:"))
        self.x0_label.setText(_translate("mainWindow", "x0:"))
        self.y0_label.setText(_translate("mainWindow", "y0:"))
        self.z0_label.setText(_translate("mainWindow", "z0:"))
        self.set_fg_par_button.setText(_translate("mainWindow", "set grid parameters"))
        self.calc_fg_button.setText(_translate("mainWindow", "calculate focal grid"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.fg_tab), _translate("mainWindow", "Focal Grid"))
        self.frame_raw_label.setText(_translate("mainWindow", "frame"))
        self.set_par_button.setText(_translate("mainWindow", "set parameters"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.fit_tab), _translate("mainWindow", "Scaling"))
        self.frame_seg_label.setText(_translate("mainWindow", "frame"))
        self.body_th_label.setText(_translate("mainWindow", "body threshold"))
        self.wing_th_label.setText(_translate("mainWindow", "wing threshold"))
        self.sigma_label.setText(_translate("mainWindow", "sigma"))
        self.K_label.setText(_translate("mainWindow", "K"))
        self.min_body_label.setText(_translate("mainWindow", "min body size"))
        self.min_wing_label.setText(_translate("mainWindow", "min wing size"))
        self.update_button.setText(_translate("mainWindow", "update"))
        self.check_tethered.setText(_translate("mainWindow", "tethered flight"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.seg_tab), _translate("mainWindow", "Segmentation"))
        self.frame_bbox_label.setText(_translate("mainWindow", "frame"))
        self.label_6.setText(_translate("mainWindow", "w xsi"))
        self.label_5.setText(_translate("mainWindow", "w theta"))
        self.label_4.setText(_translate("mainWindow", "w length"))
        self.label_3.setText(_translate("mainWindow", "w volume"))
        self.label.setText(_translate("mainWindow", "cone angle"))
        self.label_2.setText(_translate("mainWindow", "cone height"))
        self.bbox_view_btn.setText(_translate("mainWindow", "bbox view"))
        self.blr_view_btn.setText(_translate("mainWindow", "blr view"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.pcl_tab), _translate("mainWindow", "Bounding Boxes"))
        self.label_7.setText(_translate("mainWindow", "frame nr:"))
        self.show_dest_pts.setText(_translate("mainWindow", "show dest"))
        self.show_src_pts.setText(_translate("mainWindow", "show src"))
        self.show_mdl.setText(_translate("mainWindow", "show model"))
        self.calc_align.setText(_translate("mainWindow", "calc alginment"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.model_proj_tab), _translate("mainWindow", "MBICP"))
        self.label_8.setText(_translate("mainWindow", "frame nr:"))
        self.calc_proj.setText(_translate("mainWindow", "calc projections"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.frame_proj_tab), _translate("mainWindow", "frame projections"))

from BoundingBoxWidget import BBoxWidget
from ImageProjectionsWidget import ImageProjectionsWidget
from ImageSegmentWidget import ImageSegmentWidget
from ModelProjectionWidget import ModelProjectionWidget
from ModelSelectWidget import ModelSelectWidget
from ScaleModelWidget import ScaleModelWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

